# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Practice_17_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    cnt = 0
    
    def setupUi(self, MainWindow):
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.cnt__test = QtWidgets.QLCDNumber(self.centralwidget)
        self.cnt__test.setObjectName("cnt__test")
        self.gridLayout.addWidget(self.cnt__test, 1, 0, 1, 1)
        self.lbl__test = QtWidgets.QLabel(self.centralwidget)
        self.lbl__test.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        font.setPointSize(20)
        self.lbl__test.setFont(font)
        self.lbl__test.setObjectName("lbl__test")
        self.gridLayout.addWidget(self.lbl__test, 0, 0, 1, 1)
        self.btn__cnt = QtWidgets.QPushButton(self.centralwidget)
        self.btn__cnt.setCheckable(False)
        self.btn__cnt.setChecked(False)
        self.btn__cnt.setObjectName("btn__cnt")
        self.gridLayout.addWidget(self.btn__cnt, 3, 0, 1, 1)
        self.btn__reset = QtWidgets.QPushButton(self.centralwidget)
        self.btn__reset.setObjectName("btn__reset")
        self.gridLayout.addWidget(self.btn__reset, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.btn__cnt.clicked.connect(self.btn_clicked)         # 클릭 이벤트 발생시 함수 실행
        self.btn__reset.clicked.connect(self.reset)             # reset 클릭 시 함수 실행

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def btn_clicked(self):                                      # 클릭 이벤트 발생시

        self.cnt += 1                                           # cnt +1
        self.cnt__test.display(self.cnt)                        # 숫자의 값은 cnt

        if 20 > self.cnt >= 10:                                 # 10 번 이상 누르면 문구가 바뀌게끔

            self.lbl__test.setText("GREAT! You have to - - - - - - - - - - CLICK MORE!!")

        elif self.cnt >= 20:                                    # 20 번 이상 누르면 문구가 바뀌게끔

            self.lbl__test.setText("WOW! Now Press - - - - - - - - - - - - - - - RESET!")


    def reset(self):                                            # 숫자 리셋

        if self.cnt > 0:                                        # reset이 실행될때 문구 원상복구

            self.lbl__test.setText("Hello World!  - - - - - - - - - - - - - - -  Click!")
        
        self.cnt = 0
        self.cnt__test.display(self.cnt)
        
    def retranslateUi(self, MainWindow):
        
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QtPractice"))
        self.lbl__test.setText(_translate("MainWindow", "Hello World!  - - - - - - - - - - - - - - -  Click!"))
        self.btn__cnt.setText(_translate("MainWindow", "OK"))
        self.btn__reset.setText(_translate("MainWindow", "RESET"))


if __name__ == "__main__":
    
    import sys
    
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
