# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P_18_2_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    
    def setupUi(self, MainWindow):
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 625)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt__edit = QtWidgets.QTextEdit(self.centralwidget)
        self.txt__edit.setGeometry(QtCore.QRect(9, 9, 781, 411))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code Light")
        font.setPointSize(12)
        self.txt__edit.setFont(font)
        self.txt__edit.setObjectName("txt__edit")
        self.txt__open = QtWidgets.QTextEdit(self.centralwidget)
        self.txt__open.setGeometry(QtCore.QRect(10, 470, 641, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code Light")
        font.setPointSize(12)
        self.txt__open.setFont(font)
        self.txt__open.setObjectName("txt__open")
        self.txt__save = QtWidgets.QTextEdit(self.centralwidget)
        self.txt__save.setGeometry(QtCore.QRect(10, 510, 641, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code Light")
        font.setPointSize(12)
        self.txt__save.setFont(font)
        self.txt__save.setObjectName("txt__save")
        self.btn__open = QtWidgets.QPushButton(self.centralwidget)
        self.btn__open.setGeometry(QtCore.QRect(660, 470, 131, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn__open.setFont(font)
        self.btn__open.setObjectName("btn__open")
        self.btn__save = QtWidgets.QPushButton(self.centralwidget)
        self.btn__save.setGeometry(QtCore.QRect(660, 510, 131, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn__save.setFont(font)
        self.btn__save.setObjectName("btn__save")
        self.btn__reset = QtWidgets.QPushButton(self.centralwidget)
        self.btn__reset.setGeometry(QtCore.QRect(660, 550, 131, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn__reset.setFont(font)
        self.btn__reset.setObjectName("btn__reset")
        self.lbl__status = QtWidgets.QLabel(self.centralwidget)
        self.lbl__status.setGeometry(QtCore.QRect(10, 430, 781, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(15)
        self.lbl__status.setFont(font)
        self.lbl__status.setText("")
        self.lbl__status.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl__status.setObjectName("lbl__status")
        self.rb__s_ansi = QtWidgets.QRadioButton(self.centralwidget)
        self.rb__s_ansi.setGeometry(QtCore.QRect(569, 550, 81, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        self.rb__s_ansi.setFont(font)
        self.rb__s_ansi.setObjectName("rb__s_ansi")
        self.rb__s_utf = QtWidgets.QRadioButton(self.centralwidget)
        self.rb__s_utf.setGeometry(QtCore.QRect(470, 550, 81, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        self.rb__s_utf.setFont(font)
        self.rb__s_utf.setIconSize(QtCore.QSize(12, 12))
        self.rb__s_utf.setObjectName("rb__s_utf")
        self.rb__o_utf = QtWidgets.QRadioButton(self.centralwidget)
        self.rb__o_utf.setGeometry(QtCore.QRect(140, 550, 81, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        self.rb__o_utf.setFont(font)
        self.rb__o_utf.setIconSize(QtCore.QSize(12, 12))
        self.rb__o_utf.setObjectName("rb__o_utf")
        self.rb__o_ansi = QtWidgets.QRadioButton(self.centralwidget)
        self.rb__o_ansi.setGeometry(QtCore.QRect(239, 550, 81, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        self.rb__o_ansi.setFont(font)
        self.rb__o_ansi.setObjectName("rb__o_ansi")
        self.lbl__otype = QtWidgets.QLabel(self.centralwidget)
        self.lbl__otype.setEnabled(False)
        self.lbl__otype.setGeometry(QtCore.QRect(19, 550, 101, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl__otype.setFont(font)
        self.lbl__otype.setObjectName("lbl__otype")
        self.lbl__stype = QtWidgets.QLabel(self.centralwidget)
        self.lbl__stype.setEnabled(False)
        self.lbl__stype.setGeometry(QtCore.QRect(340, 550, 121, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl__stype.setFont(font)
        self.lbl__stype.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl__stype.setObjectName("lbl__stype")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.txt__open.setEnabled(False)
        self.txt__save.setEnabled(False)

        self.btn__open.clicked.connect(self.open)
        self.btn__save.clicked.connect(self.save)
        self.btn__reset.clicked.connect(self.reset)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def open_select(self):

        path = QtWidgets.QFileDialog.getOpenFileName(self, "Select Directory")
     
        return path[0]

    def save_select(self):

        path = QtWidgets.QFileDialog.getSaveFileName(self, "Select Directory")
     
        return path[0]

    def open_type(self):

        if self.rb__o_utf.isChecked() : e = "utf-8"
        elif self.rb__o_ansi.isChecked() : e = "cp949"

        return e

    def save_type(self):

        if self.rb__s_utf.isChecked(): e = "utf-8"
        elif self.rb__s_ansi.isChecked(): e = "cp949"

        return e

    def open(self):
        
        try:

            self.txt__edit.setEnabled(True)
            self.txt__edit.setText("")
            self.txt__save.setText("")            
            
            path = self.open_select()
            self.txt__open.setText(path)

            e = self.open_type()
            print(e)
            
            f = open(path, "r", encoding = e)

            for i in f:
            
                temp = self.txt__edit.toPlainText()
                self.txt__edit.setText(f"{temp}{i}")

            f.close()

            self.lbl__status.setText("파일이 정상적으로 열렸습니다.")
            
        except:
            
            self.lbl__status.setText("다시 시도해 주세요.")

    def save(self):
        
        try:
            
            temp = self.txt__edit.toPlainText()
            
            path = self.save_select()            
            self.txt__save.setText(path)

            e = self.save_type()

            f = open(path, "w", encoding = e)

            f.write(temp)

            f.close()

            self.lbl__status.setText("파일이 정상적으로 저장되었습니다.")
            self.txt__edit.setEnabled(False)
            
        except:
            
            self.lbl__status.setText("다시 시도해 주세요.")

    def reset(self):

        self.txt__edit.setText("")
        self.txt__open.setText("")
        self.txt__save.setText("")
        self.lbl__status.setText("")
        self.txt__edit.setEnabled(True)
            
    def retranslateUi(self, MainWindow):
        
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TEXT EDITOR"))
        self.btn__open.setText(_translate("MainWindow", "OPEN"))
        self.btn__save.setText(_translate("MainWindow", "SAVE"))
        self.btn__reset.setText(_translate("MainWindow", "RESET"))
        self.rb__s_ansi.setText(_translate("MainWindow", "ANSI"))
        self.rb__s_utf.setText(_translate("MainWindow", "UTF-8"))
        self.rb__o_utf.setText(_translate("MainWindow", "UTF-8"))
        self.rb__o_ansi.setText(_translate("MainWindow", "ANSI"))
        self.lbl__otype.setText(_translate("MainWindow", "OPEN TYPE"))
        self.lbl__stype.setText(_translate("MainWindow", "SAVE TYPE"))

if __name__ == "__main__":
    
    import sys
    
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
