# Generated by Django 2.0.13 on 2022-12-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.TextField(blank=True, db_column='ONE', null=True)),
                ('two', models.TextField(blank=True, db_column='TWO', null=True)),
                ('thr', models.TextField(blank=True, db_column='THR', null=True)),
                ('x', models.IntegerField(blank=True, db_column='X', null=True)),
                ('y', models.IntegerField(blank=True, db_column='Y', null=True)),
                ('lng', models.TextField(blank=True, db_column='LNG', null=True)),
                ('lat', models.TextField(blank=True, db_column='LAT', null=True)),
            ],
            options={
                'db_table': 'LOCATION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Srtfcst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.TextField(blank=True, db_column='Datetime', null=True, unique=True)),
                ('t1h', models.TextField(blank=True, db_column='T1H', null=True)),
                ('rn1', models.TextField(blank=True, db_column='RN1', null=True)),
                ('sky', models.TextField(blank=True, db_column='SKY', null=True)),
                ('reh', models.TextField(blank=True, db_column='REH', null=True)),
                ('pty', models.TextField(blank=True, db_column='PTY', null=True)),
                ('vec', models.TextField(blank=True, db_column='VEC', null=True)),
                ('wsd', models.TextField(blank=True, db_column='WSD', null=True)),
                ('uuu', models.TextField(blank=True, db_column='UUU', null=True)),
                ('vvv', models.TextField(blank=True, db_column='VVV', null=True)),
                ('lgt', models.TextField(blank=True, db_column='LGT', null=True)),
            ],
            options={
                'db_table': 'SrtFcst',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Srtncst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.TextField(blank=True, db_column='Datetime', null=True, unique=True)),
                ('t1h', models.TextField(blank=True, db_column='T1H', null=True)),
                ('rn1', models.TextField(blank=True, db_column='RN1', null=True)),
                ('reh', models.TextField(blank=True, db_column='REH', null=True)),
                ('pty', models.TextField(blank=True, db_column='PTY', null=True)),
                ('vec', models.TextField(blank=True, db_column='VEC', null=True)),
                ('wsd', models.TextField(blank=True, db_column='WSD', null=True)),
                ('uuu', models.TextField(blank=True, db_column='UUU', null=True)),
                ('vvv', models.TextField(blank=True, db_column='VVV', null=True)),
            ],
            options={
                'db_table': 'SrtNcst',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vilagefcst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.TextField(blank=True, db_column='Datetime', null=True, unique=True)),
                ('pop', models.TextField(blank=True, db_column='POP', null=True)),
                ('pty', models.TextField(blank=True, db_column='PTY', null=True)),
                ('pcp', models.TextField(blank=True, db_column='PCP', null=True)),
                ('reh', models.TextField(blank=True, db_column='REH', null=True)),
                ('sno', models.TextField(blank=True, db_column='SNO', null=True)),
                ('sky', models.TextField(blank=True, db_column='SKY', null=True)),
                ('tmp', models.TextField(blank=True, db_column='TMP', null=True)),
                ('tmn', models.TextField(blank=True, db_column='TMN', null=True)),
                ('tmx', models.TextField(blank=True, db_column='TMX', null=True)),
                ('vec', models.TextField(blank=True, db_column='VEC', null=True)),
                ('wsd', models.TextField(blank=True, db_column='WSD', null=True)),
                ('uuu', models.TextField(blank=True, db_column='UUU', null=True)),
                ('vvv', models.TextField(blank=True, db_column='VVV', null=True)),
                ('wav', models.TextField(blank=True, db_column='WAV', null=True)),
            ],
            options={
                'db_table': 'VilageFcst',
                'managed': False,
            },
        ),
    ]
