# Generated by Django 2.0.13 on 2022-11-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('models', models.CharField(max_length=50)),
            ],
        ),
    ]
