# Generated by Django 2.0.13 on 2022-11-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pro_02', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='models',
            field=models.CharField(max_length=250),
        ),
    ]
